version: "3.9"

services:
  # ===== MongoDB =====
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ===== Qdrant =====
  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # ===== Redis (Celery broker) =====
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # ===== TEI Embedding Model =====
  tei-embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    container_name: tei_embedding
    restart: always
    ports:
      - "8081:80"
    command: --model-id Qwen/Qwen2.5-embedding --dtype float32 --max-batch-tokens 8192
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # ===== TEI Reranker =====
  tei-reranker:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    container_name: tei_reranker
    restart: always
    ports:
      - "8082:80"
    command: --model-id BAAI/bge-reranker-v2-m3 --dtype float32 --max-batch-tokens 8192
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  mongo_data:
  qdrant_data:
